spring:
  application:
    name: demo-consumer

dubbo:
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
    id: my-registry
  protocol:
    port: 20882
    name: dubbo
    id: dubbo
  application:
    name: demo-consumer
    id: demo-consumer
    qosEnable: true
    qosPort: 22224

registry:
  other:
    protocol: zookeeper
    address: 127.0.0.1:2181
    id: other
